### ISSUE TITLE
Small bug for project namespace

### ISSUE THREAD

**Issue by kjhf** [invalidCards/WikiOperatingBuddy#41]
From Inkipedia chat today, where Wiki Operating Buddy is set up to follow Inkipedia links.
I think there is confusion between cross-wiki link functionality and the project namespace.

User: [[Inkipedia:Policy/Manual of Style]]
(no response)

User: [[Inkipedia:Policy]]
Wiki Operating Buddy:
Wiki links detected:
https://splatoonwiki.org/wiki/Inkipedia:Policy/Notability_Policy

User: [[Project:Policy]]
Wiki Operating Buddy:
Wiki links detected:
http://splatoonwiki.org/wiki/Inkipedia:Policy

User: [[Project:Policy/Manual of Style]]
Wiki Operating Buddy:
http://splatoonwiki.org/wiki/Inkipedia:Policy/Manual_of_Style

User: [[Inkipedia:Policy/Manual of Style]]
(no response)

**Comment by invalidCards** [comment]
Seems to be an issue with the Splatoon Wiki API specifically, as others do properly handle article names with spaces replaced by underscores. I don't feel much for implementing a special case just for this one, so I'd urge the owners of the Splatoon wiki to fix it on their end somehow.
